version: '3.4'

services:
  reduxdemo:
    image: reduxdemo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - '.:/usr/src/app'
      - '/app/node_modules'
    ports:
      - 3005:3000
    environment:
      - CHOKIDAR_USEPOLLING=true