version: '3.4'

services:
  reactreduxdemo:
    image: reactreduxdemo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - '.:/usr/src/app'
      - '/app/node_modules'
    ports:
      - 3006:3000
    environment:
      - CHOKIDAR_USEPOLLING=true